FROM golang:1.25.4-alpine3.22
ARG AIR_VERSION=v1.63.0
RUN apk add --no-cache git ca-certificates
WORKDIR /app
RUN go install github.com/air-verse/air@${AIR_VERSION}
COPY go.mod go.sum ./
RUN go mod download
COPY . .
CMD ["air"]
